language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install libzmq3-dev
  - sudo apt-get install libprotobuf-dev
  - git submodule update --init --recursive
  - mkdir build
script:
  - cmake --build build/
